-- ============================================
-- 010: Prayer Engine — Phase 3A (MVP)
-- Confession library, personal plans, daily tracking,
-- new believer auto-track, confession of the week
-- ============================================

-- -----------------------------------------------
-- 1. confession_categories (16 categories)
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS confession_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT DEFAULT '📖',
    color TEXT DEFAULT '#5B4FC4',
    tier INTEGER DEFAULT 1,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE confession_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active categories"
    ON confession_categories FOR SELECT USING (is_active = true);

CREATE POLICY "Admin can manage categories"
    ON confession_categories FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM user_profiles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

-- Seed 16 categories
INSERT INTO confession_categories (name, description, icon, color, tier, sort_order) VALUES
('Health & Healing', 'Physical healing, emotional healing, divine health and anointing', '🏥', '#3A8F5C', 1, 1),
('Finances, Business & Provision', 'Financial breakthrough, employment, business success, God''s provision', '💰', '#D4853A', 1, 2),
('Faith, Favor & Declarations', 'Corporate confessions, favor, righteousness, walking in victory', '✨', '#5B4FC4', 1, 3),
('Identity in Christ & Personal Transformation', 'Who I am in Christ, breakthrough, letting go of the past', '🦋', '#C44B5B', 1, 4),
('Salvation & Evangelism', 'Confessing for unsaved loved ones, new converts, the Great Commission', '🌍', '#2E7D32', 1, 5),
('Daily Confessions & Morning/Evening Prayers', 'AM/PM daily rhythm, general daily prayers and declarations', '🌅', '#FF8F00', 1, 6),
('Marriage & Spouse', 'Harmonious marriage, confessions for husbands and wives, restoration', '💍', '#C44B5B', 2, 7),
('Family & Parenting', 'Children, teenagers, household blessings, family unity', '👨‍👩‍👧‍👦', '#5B4FC4', 2, 8),
('Daily Protection & Safety', 'Traveling mercies, safety, protection from harm and danger', '🛡️', '#1565C0', 2, 9),
('Church, Ministry & Kingdom Advancement', 'Pastors, church growth, revival fire, intercession for the body', '⛪', '#6A1B9A', 2, 10),
('Believing for Children & Family Expansion', 'Conception, fertility, adoption, waiting on God for children', '👶', '#E91E63', 2, 11),
('Thanksgiving & Praise Confessions', 'Gratitude, declaring God''s goodness, confessing from victory', '🙌', '#FFB300', 2, 12),
('Spiritual Warfare & Deliverance', 'Breaking curses, cleansing prayers, territorial authority in Christ', '⚔️', '#B71C1C', 3, 13),
('Justice, Legal Matters & Righteous Judgment', 'Court cases, immigration, custody, standing for justice', '⚖️', '#37474F', 3, 14),
('Grief, Loss & Comfort', 'Comfort for widows, loss of loved ones, processing grief with faith', '🕊️', '#78909C', 3, 15),
('Students, Exams & Academic Success', 'Exams, scholarships, academic calling, wisdom for learning', '📚', '#00897B', 3, 16);


-- -----------------------------------------------
-- 2. confession_templates (core content library)
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS confession_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES confession_categories(id),
    name TEXT NOT NULL,
    description TEXT,
    short_form_text TEXT,
    confessions JSONB DEFAULT '[]',
    declarations JSONB DEFAULT '[]',
    prayers JSONB DEFAULT '[]',
    scriptures JSONB DEFAULT '[]',
    tier INTEGER DEFAULT 2,
    difficulty_level TEXT DEFAULT 'beginner',
    maturity_warning BOOLEAN DEFAULT FALSE,
    recommended_duration TEXT DEFAULT 'ongoing',
    time_of_day TEXT DEFAULT 'anytime',
    is_published BOOLEAN DEFAULT FALSE,
    is_pastor_custom BOOLEAN DEFAULT FALSE,
    review_status TEXT DEFAULT 'draft',
    created_by UUID REFERENCES auth.users(id),
    source_document TEXT,
    source_attribution TEXT,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE confession_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read published templates"
    ON confession_templates FOR SELECT
    USING (is_published = true AND is_pastor_custom = false);

CREATE POLICY "Pastor sees own custom templates"
    ON confession_templates FOR SELECT
    USING (created_by = auth.uid() AND is_pastor_custom = true);

CREATE POLICY "Admin can manage all templates"
    ON confession_templates FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM user_profiles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

CREATE POLICY "Pastor can create custom templates"
    ON confession_templates FOR INSERT
    WITH CHECK (is_pastor_custom = true AND created_by = auth.uid());

CREATE INDEX idx_confession_templates_category ON confession_templates(category_id);
CREATE INDEX idx_confession_templates_published ON confession_templates(is_published);
CREATE INDEX idx_confession_templates_tier ON confession_templates(tier);
CREATE INDEX idx_confession_templates_review ON confession_templates(review_status);


-- -----------------------------------------------
-- 3. new_believer_track (7-day onboarding)
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS new_believer_track (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_number INTEGER NOT NULL,
    template_id BIGINT REFERENCES confession_templates(id) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE new_believer_track ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read track"
    ON new_believer_track FOR SELECT USING (true);

CREATE POLICY "Admin manages track"
    ON new_believer_track FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM user_profiles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );


-- -----------------------------------------------
-- 4. confession_of_the_week
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS confession_of_the_week (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT REFERENCES confession_templates(id) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    sermon_theme TEXT,
    sermon_reference TEXT,
    set_by UUID REFERENCES auth.users(id),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE confession_of_the_week ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active COTW"
    ON confession_of_the_week FOR SELECT USING (is_active = true);

CREATE POLICY "Admin manages COTW"
    ON confession_of_the_week FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM user_profiles
            WHERE user_id = auth.uid() AND role = 'admin'
        )
    );

CREATE INDEX idx_cotw_active ON confession_of_the_week(is_active, start_date, end_date);


-- -----------------------------------------------
-- 5. member_confession_plans (personal plans)
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS member_confession_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    template_id BIGINT REFERENCES confession_templates(id) NOT NULL,
    assigned_by UUID REFERENCES auth.users(id),
    assignment_note TEXT,
    plan_type TEXT DEFAULT 'ongoing',
    time_slot TEXT DEFAULT 'anytime',
    start_date DATE DEFAULT CURRENT_DATE,
    end_date DATE,
    status TEXT DEFAULT 'active',
    is_new_believer_track BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE member_confession_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User sees own plans"
    ON member_confession_plans FOR SELECT
    USING (user_id = auth.uid());

CREATE POLICY "User manages own plans"
    ON member_confession_plans FOR INSERT
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "User updates own plans"
    ON member_confession_plans FOR UPDATE
    USING (user_id = auth.uid());

CREATE POLICY "Pastor sees assigned plans"
    ON member_confession_plans FOR SELECT
    USING (assigned_by = auth.uid());

CREATE POLICY "Pastor can assign to viewable members"
    ON member_confession_plans FOR INSERT
    WITH CHECK (
        assigned_by = auth.uid()
        AND public.can_view_user(user_id)
    );

CREATE INDEX idx_member_plans_user ON member_confession_plans(user_id);
CREATE INDEX idx_member_plans_user_status ON member_confession_plans(user_id, status);
CREATE INDEX idx_member_plans_assigned_by ON member_confession_plans(assigned_by);
CREATE INDEX idx_member_plans_new_believer ON member_confession_plans(user_id, is_new_believer_track);


-- -----------------------------------------------
-- 6. confession_completions (daily log)
-- -----------------------------------------------
CREATE TABLE IF NOT EXISTS confession_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    plan_id BIGINT REFERENCES member_confession_plans(id) NOT NULL,
    completed_date DATE NOT NULL DEFAULT CURRENT_DATE,
    time_slot TEXT,
    reflection_note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, plan_id, completed_date, time_slot)
);

ALTER TABLE confession_completions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User manages own completions"
    ON confession_completions FOR ALL
    USING (user_id = auth.uid());

CREATE POLICY "Pastor views completions for prescribed plans"
    ON confession_completions FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM member_confession_plans mcp
            WHERE mcp.id = confession_completions.plan_id
            AND mcp.assigned_by = auth.uid()
        )
    );

CREATE INDEX idx_completions_user_date ON confession_completions(user_id, completed_date);
CREATE INDEX idx_completions_plan ON confession_completions(plan_id);


-- -----------------------------------------------
-- 7. Seed Tier 1 Confession Templates
-- -----------------------------------------------

-- CAT-01: Health & Healing
INSERT INTO confession_templates (category_id, name, description, short_form_text, confessions, declarations, prayers, scriptures, tier, difficulty_level, recommended_duration, time_of_day, is_published, review_status, sort_order) VALUES
(1, 'Divine Healing Confession', 'For those believing God for physical healing and restoration',
'By His stripes I am healed — Isaiah 53:5
I am the Lord''s healed one — Exodus 15:26
No sickness shall dwell in my body — Deuteronomy 7:15',
'[{"text":"By the stripes of Jesus Christ, I am healed and made whole","scripture_ref":"Isaiah 53:5"},{"text":"The Lord is Jehovah Rapha, the God who heals me, and I receive my healing now","scripture_ref":"Exodus 15:26"},{"text":"I confess that no sickness or disease has any right to operate in my body","scripture_ref":"Deuteronomy 7:15"},{"text":"The same Spirit that raised Christ from the dead dwells in me and quickens my mortal body","scripture_ref":"Romans 8:11"},{"text":"I am redeemed from the curse of sickness and disease","scripture_ref":"Galatians 3:13"}]',
'[{"text":"I declare that I walk in divine health every day of my life","scripture_ref":"3 John 1:2"},{"text":"I declare that my body is the temple of the Holy Spirit and I honor God with it","scripture_ref":"1 Corinthians 6:19"},{"text":"I declare that with long life God satisfies me and shows me His salvation","scripture_ref":"Psalm 91:16"}]',
'[{"text":"Father, I thank You that You sent Your Word and healed me. I receive total healing and restoration in my body, mind, and spirit. I reject every symptom and stand on Your promises. In Jesus'' name, Amen."}]',
'["Isaiah 53:5","Exodus 15:26","Deuteronomy 7:15","Romans 8:11","Galatians 3:13","3 John 1:2","Psalm 91:16","1 Corinthians 6:19"]',
1, 'beginner', '21_days', 'morning', true, 'approved', 1),

(1, 'Emotional Healing & Inner Peace', 'For those dealing with past trauma, anxiety, and emotional wounds',
'God heals the brokenhearted — Psalm 147:3
His peace guards my heart and mind — Philippians 4:7
I cast all my anxiety on Him — 1 Peter 5:7',
'[{"text":"I confess that God heals the brokenhearted and binds up their wounds, and I receive that healing now","scripture_ref":"Psalm 147:3"},{"text":"I confess that the peace of God which surpasses all understanding guards my heart and my mind","scripture_ref":"Philippians 4:7"},{"text":"I cast all my anxiety, worry, and fear upon the Lord because He cares for me","scripture_ref":"1 Peter 5:7"},{"text":"I confess that God has not given me a spirit of fear but of power, love, and a sound mind","scripture_ref":"2 Timothy 1:7"}]',
'[{"text":"I declare that I am being renewed in the spirit of my mind daily","scripture_ref":"Ephesians 4:23"},{"text":"I declare that old things have passed away and all things have become new in my life","scripture_ref":"2 Corinthians 5:17"},{"text":"I declare that the joy of the Lord is my strength and I will not be moved","scripture_ref":"Nehemiah 8:10"}]',
'[{"text":"Lord, I bring every hurt, every memory, every wound to You. You are the restorer of my soul. I release the past and receive Your peace that passes understanding. Heal me from the inside out. In Jesus'' name, Amen."}]',
'["Psalm 147:3","Philippians 4:7","1 Peter 5:7","2 Timothy 1:7","Ephesians 4:23","2 Corinthians 5:17","Nehemiah 8:10"]',
1, 'beginner', '21_days', 'evening', true, 'approved', 2);

-- CAT-02: Finances, Business & Provision
INSERT INTO confession_templates (category_id, name, description, short_form_text, confessions, declarations, prayers, scriptures, tier, difficulty_level, recommended_duration, time_of_day, is_published, review_status, sort_order) VALUES
(2, 'Financial Breakthrough Confession', 'For those believing God for financial provision and debt freedom',
'God supplies all my needs — Philippians 4:19
I am blessed to be a blessing — Genesis 12:2
The Lord opens the windows of heaven — Malachi 3:10',
'[{"text":"I confess that my God shall supply all my needs according to His riches in glory by Christ Jesus","scripture_ref":"Philippians 4:19"},{"text":"I confess that I am blessed to be a blessing and that the blessing of Abraham is mine","scripture_ref":"Genesis 12:2"},{"text":"I confess that as I honour the Lord with my substance, my barns are filled with plenty","scripture_ref":"Proverbs 3:9-10"},{"text":"I confess that the Lord has pleasure in the prosperity of His servant","scripture_ref":"Psalm 35:27"}]',
'[{"text":"I declare that I am the head and not the tail, above and not beneath in my finances","scripture_ref":"Deuteronomy 28:13"},{"text":"I declare that debt has no hold on my life and I am moving into financial freedom","scripture_ref":"Romans 13:8"},{"text":"I declare that every seed I sow produces a harvest of abundance","scripture_ref":"2 Corinthians 9:6"},{"text":"I declare that God opens doors of provision that no man can shut","scripture_ref":"Revelation 3:8"}]',
'[{"text":"Father, I trust You as my provider. I bring my finances before You and ask for wisdom, open doors, and supernatural provision. I commit to be a faithful steward and a generous giver. Break every cycle of lack in my life. In Jesus'' name, Amen."}]',
'["Philippians 4:19","Genesis 12:2","Proverbs 3:9-10","Psalm 35:27","Deuteronomy 28:13","Romans 13:8","2 Corinthians 9:6","Revelation 3:8","Malachi 3:10"]',
1, 'beginner', '21_days', 'morning', true, 'approved', 1),

(2, 'Business & Career Success', 'For those believing God for business growth, job favour, and career direction',
'The Lord makes my way prosperous — Joshua 1:8
Favour surrounds me like a shield — Psalm 5:12
God gives power to get wealth — Deuteronomy 8:18',
'[{"text":"I confess that I meditate on God''s Word day and night and He makes my way prosperous and gives me good success","scripture_ref":"Joshua 1:8"},{"text":"I confess that the Lord has given me power to get wealth to establish His covenant","scripture_ref":"Deuteronomy 8:18"},{"text":"I confess that whatever I put my hand to prospers because the Lord is with me","scripture_ref":"Deuteronomy 28:8"},{"text":"I confess that God grants me favour in my workplace and business dealings","scripture_ref":"Psalm 5:12"}]',
'[{"text":"I declare that I am anointed for business success and kingdom impact","scripture_ref":"Isaiah 45:3"},{"text":"I declare that divine ideas, strategies, and connections come to me","scripture_ref":"James 1:5"},{"text":"I declare that I am promoted and elevated in my career by the hand of God","scripture_ref":"Psalm 75:6-7"}]',
'[{"text":"Lord, I commit my work to You. Guide my decisions, give me wisdom in every negotiation, and let Your favour go before me. Use my career and business as a platform for Your glory. In Jesus'' name, Amen."}]',
'["Joshua 1:8","Deuteronomy 8:18","Deuteronomy 28:8","Psalm 5:12","Isaiah 45:3","James 1:5","Psalm 75:6-7"]',
1, 'beginner', '21_days', 'morning', true, 'approved', 2);

-- CAT-03: Faith, Favor & Declarations
INSERT INTO confession_templates (category_id, name, description, short_form_text, confessions, declarations, prayers, scriptures, tier, difficulty_level, recommended_duration, time_of_day, is_published, review_status, sort_order) VALUES
(3, 'Walking in Victory', 'Daily declarations of faith and favour for victorious living',
'I am more than a conqueror — Romans 8:37
I can do all things through Christ — Philippians 4:13
Greater is He that is in me — 1 John 4:4',
'[{"text":"I confess that I am more than a conqueror through Him who loved me","scripture_ref":"Romans 8:37"},{"text":"I confess that I can do all things through Christ who strengthens me","scripture_ref":"Philippians 4:13"},{"text":"I confess that greater is He that is in me than he that is in the world","scripture_ref":"1 John 4:4"},{"text":"I confess that no weapon formed against me shall prosper","scripture_ref":"Isaiah 54:17"},{"text":"I confess that God always causes me to triumph in Christ Jesus","scripture_ref":"2 Corinthians 2:14"}]',
'[{"text":"I declare that this is my season of favour and open doors","scripture_ref":"Psalm 102:13"},{"text":"I declare that goodness and mercy follow me all the days of my life","scripture_ref":"Psalm 23:6"},{"text":"I declare that I walk in the fullness of God''s plan for my life","scripture_ref":"Jeremiah 29:11"},{"text":"I declare that the favour of God surrounds me like a shield","scripture_ref":"Psalm 5:12"}]',
'[{"text":"Father, I thank You for victory in every area of my life. I walk by faith and not by sight. Your favour opens doors before me and Your grace is sufficient for every challenge. I rise in the authority You have given me. In Jesus'' name, Amen."}]',
'["Romans 8:37","Philippians 4:13","1 John 4:4","Isaiah 54:17","2 Corinthians 2:14","Psalm 102:13","Psalm 23:6","Jeremiah 29:11","Psalm 5:12"]',
1, 'beginner', 'ongoing', 'morning', true, 'approved', 1);

-- CAT-04: Identity in Christ
INSERT INTO confession_templates (category_id, name, description, short_form_text, confessions, declarations, prayers, scriptures, tier, difficulty_level, recommended_duration, time_of_day, is_published, review_status, sort_order) VALUES
(4, 'Who I Am in Christ', 'Foundation confessions declaring your identity as a child of God',
'I am a new creation in Christ — 2 Corinthians 5:17
I am chosen and dearly loved — Colossians 3:12
I am God''s workmanship — Ephesians 2:10',
'[{"text":"I confess that I am a new creation in Christ — old things have passed away, all things have become new","scripture_ref":"2 Corinthians 5:17"},{"text":"I confess that I am chosen by God, holy and dearly loved","scripture_ref":"Colossians 3:12"},{"text":"I confess that I am God''s workmanship, created in Christ Jesus for good works","scripture_ref":"Ephesians 2:10"},{"text":"I confess that I am the righteousness of God in Christ Jesus","scripture_ref":"2 Corinthians 5:21"},{"text":"I confess that I am accepted in the Beloved","scripture_ref":"Ephesians 1:6"}]',
'[{"text":"I declare that I am who God says I am — blessed, favoured, and anointed","scripture_ref":"Psalm 139:14"},{"text":"I declare that nothing can separate me from the love of God","scripture_ref":"Romans 8:38-39"},{"text":"I declare that I have the mind of Christ and I think with wisdom and clarity","scripture_ref":"1 Corinthians 2:16"}]',
'[{"text":"Father, I thank You that You knew me before I was formed and You have a purpose for my life. I reject every lie of the enemy about my identity and I stand on who Your Word says I am. I am Yours and You are mine. In Jesus'' name, Amen."}]',
'["2 Corinthians 5:17","Colossians 3:12","Ephesians 2:10","2 Corinthians 5:21","Ephesians 1:6","Psalm 139:14","Romans 8:38-39","1 Corinthians 2:16"]',
1, 'beginner', '21_days', 'morning', true, 'approved', 1);

-- CAT-05: Salvation & Evangelism
INSERT INTO confession_templates (category_id, name, description, short_form_text, confessions, declarations, prayers, scriptures, tier, difficulty_level, recommended_duration, time_of_day, is_published, review_status, sort_order) VALUES
(5, 'Confessing for the Unsaved', 'Confessions and prayers for the salvation of loved ones',
'God desires all to be saved — 1 Timothy 2:4
The gospel is the power of God unto salvation — Romans 1:16
No one is beyond God''s reach — 2 Peter 3:9',
'[{"text":"I confess that God desires all people to be saved and come to the knowledge of the truth","scripture_ref":"1 Timothy 2:4"},{"text":"I confess that the gospel is the power of God unto salvation for everyone who believes","scripture_ref":"Romans 1:16"},{"text":"I confess that the Lord is not willing that any should perish but that all should come to repentance","scripture_ref":"2 Peter 3:9"},{"text":"I confess that the eyes of my loved ones'' understanding are being enlightened by the Holy Spirit","scripture_ref":"Ephesians 1:18"}]',
'[{"text":"I declare that my household shall be saved — I and my house will serve the Lord","scripture_ref":"Acts 16:31"},{"text":"I declare that every stronghold blinding my loved ones is broken in Jesus'' name","scripture_ref":"2 Corinthians 4:4"},{"text":"I declare that labourers are sent across the path of my unsaved family members","scripture_ref":"Matthew 9:38"}]',
'[{"text":"Father, I bring my unsaved loved ones before You. Open their eyes, soften their hearts, and send people across their path who will speak Your truth in love. I stand in the gap for their salvation. In Jesus'' name, Amen."}]',
'["1 Timothy 2:4","Romans 1:16","2 Peter 3:9","Ephesians 1:18","Acts 16:31","2 Corinthians 4:4","Matthew 9:38"]',
1, 'beginner', '21_days', 'evening', true, 'approved', 1);

-- CAT-06: Daily Confessions & Morning/Evening Prayers
INSERT INTO confession_templates (category_id, name, description, short_form_text, confessions, declarations, prayers, scriptures, tier, difficulty_level, recommended_duration, time_of_day, is_published, review_status, sort_order) VALUES
(6, 'Morning Declarations', 'Start your day by declaring God''s promises over your life',
'This is the day the Lord has made — Psalm 118:24
His mercies are new every morning — Lamentations 3:23
I am strengthened with might by His Spirit — Ephesians 3:16',
'[{"text":"I confess that this is the day the Lord has made and I will rejoice and be glad in it","scripture_ref":"Psalm 118:24"},{"text":"I confess that God''s mercies are new every morning and great is His faithfulness","scripture_ref":"Lamentations 3:22-23"},{"text":"I confess that I am strengthened with might by His Spirit in my inner man","scripture_ref":"Ephesians 3:16"},{"text":"I confess that the Lord directs my steps and orders my path today","scripture_ref":"Proverbs 16:9"}]',
'[{"text":"I declare that today is a day of favour, breakthrough, and divine appointments","scripture_ref":"Psalm 5:12"},{"text":"I declare that I walk in wisdom, discernment, and the fear of the Lord today","scripture_ref":"Proverbs 2:6"},{"text":"I declare that everything I touch today is blessed and prospers","scripture_ref":"Deuteronomy 28:8"},{"text":"I declare that angels are encamped around me and my family today","scripture_ref":"Psalm 34:7"}]',
'[{"text":"Good morning, Father. I dedicate this day to You. Fill me with Your Spirit, guide my words, direct my steps, and use me for Your glory. Let Your will be done in my life today. In Jesus'' name, Amen."}]',
'["Psalm 118:24","Lamentations 3:22-23","Ephesians 3:16","Proverbs 16:9","Psalm 5:12","Proverbs 2:6","Deuteronomy 28:8","Psalm 34:7"]',
1, 'beginner', 'ongoing', 'morning', true, 'approved', 1),

(6, 'Evening Gratitude & Rest', 'End your day with thanksgiving and declarations of peaceful rest',
'He gives His beloved sleep — Psalm 127:2
I will lie down in peace — Psalm 4:8
His faithfulness endures through the night — Psalm 92:2',
'[{"text":"I confess that the Lord gives His beloved sweet and restful sleep","scripture_ref":"Psalm 127:2"},{"text":"I confess that I lie down in peace and sleep, for the Lord alone makes me dwell in safety","scripture_ref":"Psalm 4:8"},{"text":"I confess that God''s faithfulness continues through the night and into the morning","scripture_ref":"Psalm 92:2"},{"text":"I confess that the Lord watches over me while I sleep and refreshes my body and soul","scripture_ref":"Psalm 121:4"}]',
'[{"text":"I declare that tonight I sleep under the shadow of the Almighty","scripture_ref":"Psalm 91:1"},{"text":"I declare that tomorrow brings fresh mercies and new opportunities","scripture_ref":"Lamentations 3:23"},{"text":"I declare that every plan of the enemy against my rest is nullified in Jesus'' name","scripture_ref":"Isaiah 54:17"}]',
'[{"text":"Father, I thank You for this day — for every blessing, every lesson, every provision. Forgive me where I fell short. I release every burden into Your hands and I receive Your rest tonight. Refresh me for a new day. In Jesus'' name, Amen."}]',
'["Psalm 127:2","Psalm 4:8","Psalm 92:2","Psalm 121:4","Psalm 91:1","Lamentations 3:23","Isaiah 54:17"]',
1, 'beginner', 'ongoing', 'evening', true, 'approved', 2);

-- -----------------------------------------------
-- 8. Seed New Believer Track templates
-- -----------------------------------------------
-- These use category_id 4 (Identity in Christ) primarily

INSERT INTO confession_templates (category_id, name, description, short_form_text, confessions, declarations, prayers, scriptures, tier, difficulty_level, recommended_duration, time_of_day, is_published, review_status, sort_order)
VALUES
-- NB Day 1: Who I Am in Christ
(4, 'Day 1: Who I Am in Christ', 'Your identity as a child of God — the foundation of your faith walk',
'I am a child of God — John 1:12
I am fearfully and wonderfully made — Psalm 139:14
I am loved with an everlasting love — Jeremiah 31:3',
'[{"text":"I am a child of God, born of His Spirit","scripture_ref":"John 1:12"},{"text":"I am fearfully and wonderfully made by the Creator of heaven and earth","scripture_ref":"Psalm 139:14"},{"text":"I am loved with an everlasting love that never fails","scripture_ref":"Jeremiah 31:3"}]',
'[{"text":"I declare that I belong to God and nothing can change that","scripture_ref":"Romans 8:38-39"},{"text":"I declare that God has a good plan for my life","scripture_ref":"Jeremiah 29:11"}]',
'[{"text":"Father, thank You for making me Your child. Help me to see myself the way You see me — loved, chosen, and full of purpose. In Jesus'' name, Amen."}]',
'["John 1:12","Psalm 139:14","Jeremiah 31:3","Romans 8:38-39","Jeremiah 29:11"]',
1, 'beginner', '7_days', 'morning', true, 'approved', 100),

-- NB Day 2: My Salvation is Secure
(5, 'Day 2: My Salvation is Secure', 'Assurance that your salvation is a settled matter',
'I am saved by grace through faith — Ephesians 2:8
Nothing can separate me from God''s love — Romans 8:39
My name is written in heaven — Luke 10:20',
'[{"text":"I am saved by grace through faith — it is the gift of God","scripture_ref":"Ephesians 2:8"},{"text":"Nothing can separate me from the love of God in Christ Jesus","scripture_ref":"Romans 8:39"},{"text":"My name is written in the Lamb''s book of life","scripture_ref":"Luke 10:20"}]',
'[{"text":"I declare that I have passed from death to life","scripture_ref":"John 5:24"},{"text":"I declare that Jesus is my Lord and Saviour and I am forever His","scripture_ref":"Romans 10:9"}]',
'[{"text":"Lord Jesus, thank You for saving me. I believe in my heart and confess with my mouth that You are Lord. My salvation is secure in You. Amen."}]',
'["Ephesians 2:8","Romans 8:39","Luke 10:20","John 5:24","Romans 10:9"]',
1, 'beginner', '7_days', 'morning', true, 'approved', 101),

-- NB Day 3: I Walk by Faith
(3, 'Day 3: I Walk by Faith', 'Building your faith muscle with daily declarations',
'Faith is the substance of things hoped for — Hebrews 11:1
I walk by faith, not by sight — 2 Corinthians 5:7
All things are possible to those who believe — Mark 9:23',
'[{"text":"I walk by faith and not by sight, trusting God in every situation","scripture_ref":"2 Corinthians 5:7"},{"text":"My faith is the substance of things hoped for, the evidence of things not yet seen","scripture_ref":"Hebrews 11:1"},{"text":"All things are possible because I believe","scripture_ref":"Mark 9:23"}]',
'[{"text":"I declare that my faith grows stronger every day as I stand on God''s Word","scripture_ref":"Romans 10:17"},{"text":"I declare that I will not waver in unbelief but stand firm in faith","scripture_ref":"Romans 4:20"}]',
'[{"text":"Father, increase my faith. Help me to trust You even when I cannot see the way. I choose faith over fear today. In Jesus'' name, Amen."}]',
'["2 Corinthians 5:7","Hebrews 11:1","Mark 9:23","Romans 10:17","Romans 4:20"]',
1, 'beginner', '7_days', 'morning', true, 'approved', 102),

-- NB Day 4: God Loves Me
(4, 'Day 4: God Loves Me', 'Meditating on the depth and reality of God''s love for you',
'God so loved the world — John 3:16
His love endures forever — Psalm 136:1
We love because He first loved us — 1 John 4:19',
'[{"text":"God so loved the world that He gave His only Son for me — that is how much I am worth to Him","scripture_ref":"John 3:16"},{"text":"God''s love for me endures forever — it never runs out and never gives up","scripture_ref":"Psalm 136:1"},{"text":"I love because He first loved me — His love is the source of everything good in my life","scripture_ref":"1 John 4:19"}]',
'[{"text":"I declare that I am deeply and unconditionally loved by the God of the universe","scripture_ref":"Romans 5:8"},{"text":"I declare that God''s love casts out every fear in my life","scripture_ref":"1 John 4:18"}]',
'[{"text":"Father, help me to truly know — not just in my head but in my heart — how wide, how long, how high, and how deep Your love is for me. Let Your love transform me from the inside out. In Jesus'' name, Amen."}]',
'["John 3:16","Psalm 136:1","1 John 4:19","Romans 5:8","1 John 4:18"]',
1, 'beginner', '7_days', 'morning', true, 'approved', 103),

-- NB Day 5: I Am Protected
(9, 'Day 5: I Am Protected', 'Confessing God''s protection and safety over your life',
'The Lord is my refuge and fortress — Psalm 91:2
He gives His angels charge over me — Psalm 91:11
No evil shall befall me — Psalm 91:10',
'[{"text":"The Lord is my refuge and my fortress — in Him I trust and I am safe","scripture_ref":"Psalm 91:2"},{"text":"God gives His angels charge over me to keep me in all my ways","scripture_ref":"Psalm 91:11"},{"text":"No evil shall befall me and no plague shall come near my dwelling","scripture_ref":"Psalm 91:10"}]',
'[{"text":"I declare that I dwell in the secret place of the Most High and rest in His shadow","scripture_ref":"Psalm 91:1"},{"text":"I declare that God is my shield, my protector, and my strong tower","scripture_ref":"Psalm 18:2"}]',
'[{"text":"Father, thank You for watching over me day and night. I trust in Your protection. Cover me and my loved ones under the shadow of Your wings. In Jesus'' name, Amen."}]',
'["Psalm 91:2","Psalm 91:11","Psalm 91:10","Psalm 91:1","Psalm 18:2"]',
1, 'beginner', '7_days', 'morning', true, 'approved', 104),

-- NB Day 6: I Have Purpose
(4, 'Day 6: I Have Purpose', 'Discovering your God-given purpose and calling',
'God has plans to prosper me — Jeremiah 29:11
I am created for good works — Ephesians 2:10
I am called according to His purpose — Romans 8:28',
'[{"text":"I confess that God has plans to prosper me and not to harm me, to give me hope and a future","scripture_ref":"Jeremiah 29:11"},{"text":"I confess that I was created in Christ Jesus for good works, which God prepared in advance for me to do","scripture_ref":"Ephesians 2:10"},{"text":"I confess that all things work together for good because I am called according to His purpose","scripture_ref":"Romans 8:28"},{"text":"I confess that the One who began a good work in me will carry it on to completion","scripture_ref":"Philippians 1:6"}]',
'[{"text":"I declare that my life has meaning, direction, and divine purpose","scripture_ref":"Proverbs 19:21"},{"text":"I declare that God''s gifts and calling in my life are irrevocable","scripture_ref":"Romans 11:29"},{"text":"I declare that I am exactly where God needs me to be, and He is working through me","scripture_ref":"Esther 4:14"}]',
'[{"text":"Father, reveal Your purpose for my life. Give me clarity on my calling and courage to pursue it. I surrender my own plans and choose Yours. Use me for Your glory in this generation. In Jesus'' name, Amen."}]',
'["Jeremiah 29:11","Ephesians 2:10","Romans 8:28","Philippians 1:6","Proverbs 19:21","Romans 11:29","Esther 4:14"]',
1, 'beginner', '7_days', 'morning', true, 'approved', 105),

-- NB Day 7: I Live by the Spirit
(3, 'Day 7: I Live by the Spirit', 'Walking in the power and fruit of the Holy Spirit',
'I am filled with the Holy Spirit — Ephesians 5:18
The Spirit helps me in my weakness — Romans 8:26
The fruit of the Spirit is mine — Galatians 5:22',
'[{"text":"I confess that I am filled with the Holy Spirit and walk in His power daily","scripture_ref":"Ephesians 5:18"},{"text":"I confess that the Spirit helps me in my weakness and intercedes for me with groanings too deep for words","scripture_ref":"Romans 8:26"},{"text":"I confess that the fruit of the Spirit — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control — is being produced in my life","scripture_ref":"Galatians 5:22-23"},{"text":"I confess that I do not walk by the flesh but by the Spirit of the living God","scripture_ref":"Romans 8:4"}]',
'[{"text":"I declare that the Holy Spirit guides me into all truth and reminds me of God''s Word","scripture_ref":"John 16:13"},{"text":"I declare that I am sensitive to the voice of the Holy Spirit and I obey His promptings","scripture_ref":"John 10:27"},{"text":"I declare that the same power that raised Jesus from the dead lives in me","scripture_ref":"Romans 8:11"}]',
'[{"text":"Holy Spirit, I welcome You into every area of my life. Lead me, fill me, and empower me. I choose to walk in step with You every day. Produce Your fruit in me and use me for Your glory. In Jesus'' name, Amen."}]',
'["Ephesians 5:18","Romans 8:26","Galatians 5:22-23","Romans 8:4","John 16:13","John 10:27","Romans 8:11"]',
1, 'beginner', '7_days', 'morning', true, 'approved', 106);

-- Link New Believer Track to templates (by sort_order 100-106)
INSERT INTO new_believer_track (day_number, template_id, is_active)
SELECT 1, id, true FROM confession_templates WHERE sort_order = 100 AND name LIKE 'Day 1:%' LIMIT 1;
INSERT INTO new_believer_track (day_number, template_id, is_active)
SELECT 2, id, true FROM confession_templates WHERE sort_order = 101 AND name LIKE 'Day 2:%' LIMIT 1;
INSERT INTO new_believer_track (day_number, template_id, is_active)
SELECT 3, id, true FROM confession_templates WHERE sort_order = 102 AND name LIKE 'Day 3:%' LIMIT 1;
INSERT INTO new_believer_track (day_number, template_id, is_active)
SELECT 4, id, true FROM confession_templates WHERE sort_order = 103 AND name LIKE 'Day 4:%' LIMIT 1;
INSERT INTO new_believer_track (day_number, template_id, is_active)
SELECT 5, id, true FROM confession_templates WHERE sort_order = 104 AND name LIKE 'Day 5:%' LIMIT 1;
INSERT INTO new_believer_track (day_number, template_id, is_active)
SELECT 6, id, true FROM confession_templates WHERE sort_order = 105 AND name LIKE 'Day 6:%' LIMIT 1;
INSERT INTO new_believer_track (day_number, template_id, is_active)
SELECT 7, id, true FROM confession_templates WHERE sort_order = 106 AND name LIKE 'Day 7:%' LIMIT 1;